# Site Settings
title: Vicky Chuqiao Yang
email: vcy@u.northwestern.edu
description: >
  Vicky Chuqiao Yang, PhD Candidate in Applied Mathematics at Northwestern University, also party of the data sciecence (IDEAS) program at Northwestern. Vicky works on mathematical models for social problems, including crime and invention in cities, and political elections. 
  
baseurl: "https://vcyang.com"
url: "https://vcyang.com"
github_username:  vicky20151
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
