# Site Settings
title: Vicky Chuqiao Yang
email: vcyang@mit.edu
description: >
  Personal website of Vicky C Yang, Assistant Professor, MIT Sloan School of Management 
  
baseurl: /
url: http://www.vcyang.com

github_username:  vicky20151
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
